common:
  acrRegistoryURL: todocr001.azurecr.io
  ingressClass: nginx
UI:
  replicaCount: 2
  image:
    name: todoui
    tag: v24
  servicePort: 80
  containerPort: 80
  host: kulphi.shop

getTask:
 replicaCount: 2
 image:
   name: gettask
   tag: v7
 host: get-task.kulphi.shop
 servicePort: 80
 containerPort: 8000
 
add-task:


delete-task:
