common:
  acrRegistoryURL: todoacr001.azurecr.io
  # ingressClass: nginx
  ingressClass: azure-application-gateway
UI:
  replicaCount: 2
  image:
    name: todoui
    tag: v28
  servicePort: 80
  containerPort: 80
  host: kulphi.shop

getTask:
 replicaCount: 2
 image:
   name: gettask
   tag: v8
 host: get-task.kulphi.shop
 servicePort: 80
 containerPort: 8000
 
deleteTask:
 replicaCount: 2
 image:
   name: deletetask
   tag: v6
 host: delete-task.kulphi.shop
 servicePort: 80
 containerPort: 8000

addTask:
 replicaCount: 2
 image:
   name: addtask
   tag: v11
 host: add-task.kulphi.shop
 servicePort: 80
 containerPort: 8000

