apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-add-deployment
spec:
  replicas: {{ .Values.addTask.replicaCount }}
  selector:
    matchLabels:
      app-name: {{ .Release.Name }}-addTask
  template:
    metadata:
      name: {{ .Release.Name }}-addTask
      labels:
        app-name: {{ .Release.Name }}-addTask
    spec:
      containers:
      - name: {{ .Release.Name }}-addTask
        image: {{ .Values.common.acrRegistoryURL }}/{{ .Values.addTask.image.name }}:{{ .Values.addTask.image.tag }}
        ports:
        - containerPort: {{ .Values.addTask.containerPort }}