apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task-service
spec:
  type: ClusterIP
  selector:
    app-name: {{ .Release.Name }}-addtask
  ports:
    - protocol: TCP
      port: {{ .Values.addTask.servicePort }}  # service ka port jis par listen karega
      targetPort: {{ .Values.addTask.containerPort }}  #container port