apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-get-task-ingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  ingressClassName: {{ .Values.common.ingressClass }}
  rules:
  - host: {{ .Values.getTask.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-get-task-service #(agar argocd par chalana hei to argocd ka server dena hoga esko kubectl get svc -n todo-argocd(namespace) se check kar sakte ho)service name mean Loadbalancer service ka naam, yha cluster ip type LB ko add kar rahe
            port: 
              number: {{ .Values.getTask.servicePort }} #service ka portnumber